### ISSUE TITLE
esbuild-plugin-html only watches the HTML file

### ISSUE THREAD

**Issue by louyshong** [chialab/rna#160]
Hi, I am struggling to setup watch mode using esbuild-plugin-html, it seems that only the HTML files specified in the entryPoints are being watched but not the JS files that are included in the script tags. Is this behaviour expected?

**Comment by cowwoc** [comment]
I am having the same problem. This is a showstopper for using this plugin.

@edoardocavazza can you please take a look?

**Comment by cowwoc** [comment]
Looking forward to trying out this fix. Do you plan to cut a release layer on today?

**Comment by edoardocavazza** [comment]
Hello @cowwoc, I have just released version 0.18.1. Let me know if it works as expected or feel free to re-open the issue.

**Comment by cowwoc** [comment]
Hi @edoardocavazza 

I don't have permission to reopen this issue, but the bug is still there. I am passing in an HTML entry point that contains:

```
<script type="module" src="./bundle-shoelace.mts" defer></script>
```

However, when I modify `bundle-shoelace.mts` nothing happens. If I edit the HTML directly, then the changes get picked up. So `esbuild watch` is doing the right thing, but this plugin isn't working as expected...

**Comment by cowwoc** [comment]
I think I found the bug:

```
                    if (result.watchFiles) {
                        result.watchFiles.forEach((file) => {
                            if (!watchFiles.includes(file)) {
                                watchFiles.push();
                            }
                        });
                    }
```

The bug is in line `watchFiles.push();`

**Comment by cowwoc** [comment]
I just tested the fix locally. It works!

**Comment by cowwoc** [comment]
Please merge https://github.com/chialab/rna/pull/173 and cut a new release. Thank you.
