### ISSUE TITLE
html plugin

### ISSUE THREAD

**Issue by jney** [chialab/rna#23]
Hi guys,

I am currently trying the html plugi. It looks promising but currently I am facing 2 issues:
1. It doesn't like path starting with `/`, it looks in my own `/` dir. It would be fine if we could have a root dir in options, or maybe even root dir*s*
2. It doesn't like path starting with `http://` looking in my own dir too

**Comment by jney** [comment]
I should have checked the code first there is indeed

```js
const { stdin, sourceRoot, absWorkingDir } = options;
```

So I will try it to solve my first point

**Comment by edoardocavazza** [comment]
Hello @jney! Thanks for reaching out.

I am quite sure that both cases are not handled atm, but I am going to add a filter for full urls.
I am not sure that paths starting with `/` should be collected by the build, I think that ignoring them as well should be the proper solution, since absolute urls can refer anything in the domain, even outside the base dir.

**Comment by edoardocavazza** [comment]
I have released the `v0.11.19` of the plugin, can you please check if it works for you?

**Comment by jney** [comment]
Thank you @edoardocavazza!

I just tried it now. I still have issues with url starting with `/`. Some of us are doing client side routing, which means you will serve `index.html` whatever the call is `http://example.com/` or `http://example.com/foo/bar`, so, relative urls would fail to fetch some assets.
I think it should be an option. By default absolute URI should be relative to `sourceRoot`. But you could, for sure, add an option to configure it. ie: an `ignore` keyword handling path patterns `ignore: {js:["/exist/remotely"], css: ["/foo/bar/*", "*/ignore/*"]}`.

And a last off topic point, I saw an issue about adding or not hash to `index.html`, name still change. I would be great if the name could not change.

**Comment by edoardocavazza** [comment]
If you are developing a SPA, you are probably using the `<base>` tag, right? I can enable assets collection for absolute urls that start with the href specified in the base tag, resolving urls to the build root. Is it something it can work for you?

**Comment by jney** [comment]
never used `<base>` tag,  it probably can do the job.
I just read [this](https://stackoverflow.com/questions/1889076/what-are-the-recommendations-for-html-base-tag), I don't know what to think about it, I should try it.
anyway thank you for fast replies and support

**Comment by edoardocavazza** [comment]
Hello @jney, any update on this issue or can we close it?
